In [1]:
import pandas as pd

In [2]:
ultimate_no_null_df = pd.read_csv("resources/ultimate_no_null.csv")
ultimate_no_null_df.head()

,standard_names,month,year,Confirmed,stringency_index,lat,lng,Population (2020),Density (P/Km²),Infection_rate,ISO_2,ISO_3,Infection_rate_f
0,Afghanistan,1,2020,0.0,0.000000,33.93911,67.709953,39074280,60,0.0000%,AF,AFG,0.0000
1,Afghanistan,2,2020,1.0,2.010690,33.93911,67.709953,39074280,60,0.0000%,AF,AFG,0.0000
2,Afghanistan,3,2020,174.0,40.831935,33.93911,67.709953,39074280,60,0.0004%,AF,AFG,0.0004
3,Afghanistan,4,2020,1952.0,80.740000,33.93911,67.709953,39074280,60,0.0050%,AF,AFG,0.0050
4,Afghanistan,5,2020,13081.0,84.260000,33.93911,67.709953,39074280,60,0.0335%,AF,AFG,0.0335

In [4]:
ultimate_no_null_df['standard_names'].unique().tolist()

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cabo Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Congo Republic',
 'DR Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 "Cote d'Ivoire",
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guinea',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'South Korea',
 'Kuwait',
 'Kyrgyz Republic',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'San Marino',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Eswatini',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [14]:
ultimate_no_null_df.iloc[:1]

,standard_names,month,year,Confirmed,stringency_index,lat,lng,Population (2020),Density (P/Km²),Infection_rate,ISO_2,ISO_3,Infection_rate_f
0,Afghanistan,1,2020,0.0,0.0,33.93911,67.709953,39074280,60,0.0000%,AF,AFG,0.0

In [17]:
filtered_df = ultimate_no_null_df[ultimate_no_null_df['standard_names']=='Afghanistan'].set_index('month', drop = True)
filtered_df.head()

,standard_names,year,Confirmed,stringency_index,lat,lng,Population (2020),Density (P/Km²),Infection_rate,ISO_2,ISO_3,Infection_rate_f
month,,,,,,,,,,,,
1,Afghanistan,2020,0.0,0.000000,33.93911,67.709953,39074280,60,0.0000%,AF,AFG,0.0000
2,Afghanistan,2020,1.0,2.010690,33.93911,67.709953,39074280,60,0.0000%,AF,AFG,0.0000
3,Afghanistan,2020,174.0,40.831935,33.93911,67.709953,39074280,60,0.0004%,AF,AFG,0.0004
4,Afghanistan,2020,1952.0,80.740000,33.93911,67.709953,39074280,60,0.0050%,AF,AFG,0.0050
5,Afghanistan,2020,13081.0,84.260000,33.93911,67.709953,39074280,60,0.0335%,AF,AFG,0.0335

In [21]:
filtered_df[['Confirmed']][filtered_df['standard_names']=='Afghanistan'].iloc[1:2]

       Confirmed
month
2            1.0