# Packages

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 68)
pd.options.display.float_format = '{:,.2f}'.format
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import classification_report
import joblib
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Data Import and EDA

In [4]:
df = pd.read_csv('../Resources/final_data.csv')
df.head()

,county_name,year,min_tax_rate,avg_tax_rate,max_tax_rate,murder,rape,robbery,assault,burglary,larceny,auto_theft,avg_std_cnt_ele,avg_exp_ele,avg_score_ele,min_std_cnt_ele,min_exp_ele,min_score_ele,max_std_cnt_ele,max_exp_ele,max_score_ele,avg_std_cnt_mid,avg_exp_mid,avg_score_mid,min_std_cnt_mid,min_exp_mid,min_score_mid,max_std_cnt_mid,max_exp_mid,max_score_mid,avg_std_cnt_high,avg_exp_high,avg_score_high,min_std_cnt_high,min_exp_high,min_score_high,max_std_cnt_high,max_exp_high,max_score_high,est_pop,apr_30,points_30,apr_15,points_15,num_of_bedrooms,house_value_index,median_hh_income,poverty_count,poverty_rate
0,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,1,"81,887.96",59309,38092,14.40
1,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,2,"125,858.11",59309,38092,14.40
2,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,3,"175,185.58",59309,38092,14.40
3,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,4,"245,768.02",59309,38092,14.40
4,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,5,"398,474.97",59309,38092,14.40

In [37]:
df.shape

(420, 49)

In [38]:
df.describe()

,year,min_tax_rate,avg_tax_rate,max_tax_rate,murder,rape,robbery,assault,burglary,larceny,auto_theft,avg_std_cnt_ele,avg_exp_ele,avg_score_ele,min_std_cnt_ele,min_exp_ele,min_score_ele,max_std_cnt_ele,max_exp_ele,max_score_ele,avg_std_cnt_mid,avg_exp_mid,avg_score_mid,min_std_cnt_mid,min_exp_mid,min_score_mid,max_std_cnt_mid,max_exp_mid,max_score_mid,avg_std_cnt_high,avg_exp_high,avg_score_high,min_std_cnt_high,min_exp_high,min_score_high,max_std_cnt_high,max_exp_high,max_score_high,est_pop,apr_30,points_30,apr_15,points_15,num_of_bedrooms,house_value_index,median_hh_income,poverty_count,poverty_rate
count,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00,420.00
mean,"2,018.50",1.59,3.44,6.56,14.26,67.04,288.20,514.50,851.43,"4,349.18",518.96,556.42,"12,064.25",48.63,95.10,"4,983.31",9.19,"2,286.94","21,296.51",92.18,556.42,"12,064.25",48.63,95.10,"4,983.31",9.19,"2,286.94","21,296.51",92.18,556.42,"12,064.25",48.63,95.10,"4,983.31",9.19,"2,286.94","21,296.51",92.18,"423,256.02",3.90,0.56,3.32,0.53,3.00,"324,544.60","82,945.64","39,614.07",9.34
std,1.12,0.71,1.61,5.44,19.41,52.41,335.59,474.80,566.25,"2,665.35",690.91,106.11,"1,743.04",12.41,54.15,"2,058.60",8.98,947.44,"4,211.84",7.03,106.11,"1,743.04",12.41,54.15,"2,058.60",8.98,947.44,"4,211.84",7.03,106.11,"1,743.04",12.41,54.15,"2,058.60",8.98,947.44,"4,211.84",7.03,"255,793.20",0.51,0.10,0.50,0.10,1.42,"184,559.75","18,218.80","29,938.22",3.65
min,"2,017.00",0.49,1.28,2.39,0.00,2.00,1.00,21.00,77.00,352.00,16.00,340.12,"9,387.66",20.77,0.00,337.00,1.20,643.00,"15,980.00",73.30,340.12,"9,387.66",20.77,0.00,337.00,1.20,643.00,"15,980.00",73.30,340.12,"9,387.66",20.77,0.00,337.00,1.20,643.00,"15,980.00",73.30,"62,341.00",3.11,0.48,2.60,0.45,1.00,"55,826.48","51,786.00","4,793.00",3.90
25%,"2,017.75",0.98,2.54,4.00,2.75,23.75,42.75,109.75,357.50,"2,258.25",134.75,493.58,"11,050.88",41.58,57.25,"4,189.00",2.90,"1,802.75","18,417.00",88.67,493.58,"11,050.88",41.58,57.25,"4,189.00",2.90,"1,802.75","18,417.00",88.67,493.58,"11,050.88",41.58,57.25,"4,189.00",2.90,"1,802.75","18,417.00",88.67,"148,498.25",3.73,0.49,3.11,0.47,2.00,"181,459.75","66,378.00","15,974.75",6.20
50%,"2,018.50",1.63,3.15,4.82,9.00,62.00,164.00,389.50,850.50,"4,226.00",265.50,564.46,"11,762.97",45.81,101.00,"4,804.00",5.50,"2,185.00","20,191.00",95.35,564.46,"11,762.97",45.81,101.00,"4,804.00",5.50,"2,185.00","20,191.00",95.35,564.46,"11,762.97",45.81,101.00,"4,804.00",5.50,"2,185.00","20,191.00",95.35,"446,194.50",3.96,0.51,3.33,0.48,3.00,"282,172.33","79,966.00","33,097.50",9.05
75%,"2,019.25",2.14,3.66,6.19,17.00,90.50,436.50,804.00,"1,160.75","6,732.50",649.75,626.53,"12,577.49",54.90,126.25,"6,561.00",11.95,"2,767.00","23,211.00",97.50,626.53,"12,577.49",54.90,126.25,"6,561.00",11.95,"2,767.00","23,211.00",97.50,626.53,"12,577.49",54.90,126.25,"6,561.00",11.95,"2,767.00","23,211.00",97.50,"609,182.75",4.13,0.57,3.54,0.54,4.00,"427,612.42","94,256.25","59,520.25",12.50
max,"2,020.00",3.98,9.60,29.27,103.00,253.00,"1,867.00","1,958.00","2,775.00","9,025.00","3,772.00",725.33,"17,494.12",73.26,241.00,"8,751.00",38.90,"6,298.00","33,152.00",99.20,725.33,"17,494.12",73.26,241.00,"8,751.00",38.90,"6,298.00","33,152.00",99.20,725.33,"17,494.12",73.26,241.00,"8,751.00",38.90,"6,298.00","33,152.00",99.20,"932,897.00",4.54,0.73,4.00,0.69,5.00,"1,003,742.51","119,731.00","123,806.00",18.40

In [6]:
# label encoding of counties
le = LabelEncoder()
df['county_label'] = le.fit_transform(df['county_name'])

In [7]:
df.head()

,county_name,year,min_tax_rate,avg_tax_rate,max_tax_rate,murder,rape,robbery,assault,burglary,larceny,auto_theft,avg_std_cnt_ele,avg_exp_ele,avg_score_ele,min_std_cnt_ele,min_exp_ele,min_score_ele,max_std_cnt_ele,max_exp_ele,max_score_ele,avg_std_cnt_mid,avg_exp_mid,avg_score_mid,min_std_cnt_mid,min_exp_mid,min_score_mid,max_std_cnt_mid,max_exp_mid,max_score_mid,avg_std_cnt_high,avg_exp_high,avg_score_high,min_std_cnt_high,min_exp_high,min_score_high,max_std_cnt_high,max_exp_high,max_score_high,est_pop,apr_30,points_30,apr_15,points_15,num_of_bedrooms,house_value_index,median_hh_income,poverty_count,poverty_rate,county_label
0,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,1,"81,887.96",59309,38092,14.40,0
1,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,2,"125,858.11",59309,38092,14.40,0
2,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,3,"175,185.58",59309,38092,14.40,0
3,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,4,"245,768.02",59309,38092,14.40,0
4,ATLANTIC,2017,0.96,2.91,4.69,21.00,45.00,337.00,399.00,"1,159.00","4,756.00",271.00,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,625.61,"12,472.54",36.37,118,"6,322.00",2.90,2365,"19,102.00",91.30,265446,3.99,0.50,3.27,0.49,5,"398,474.97",59309,38092,14.40,0

In [8]:
ref_df = df[['county_name','county_label']].drop_duplicates().reset_index(drop=True)
ref_df

   county_name  county_label
0     ATLANTIC             0
1       BERGEN             1
2   BURLINGTON             2
3       CAMDEN             3
4     CAPE MAY             4
5   CUMBERLAND             5
6        ESSEX             6
7   GLOUCESTER             7
8       HUDSON             8
9    HUNTERDON             9
10      MERCER            10
11   MIDDLESEX            11
12    MONMOUTH            12
13      MORRIS            13
14       OCEAN            14
15     PASSAIC            15
16       SALEM            16
17    SOMERSET            17
18      SUSSEX            18
19       UNION            19
20      WARREN            20

# Train test split

In [20]:
# feature selection
X = df.drop(["house_value_index", 'county_name', 'county_label'], axis=1)
y = df["house_value_index"]
print(X.shape, y.shape)

(420, 47) (420,)

In [21]:
# Split data into training and testing groups and scale data 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Model fit

In [22]:
# Fit the data into model
rfm = RandomForestRegressor(n_estimators=200)
rfm.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200)

In [23]:
sorted(zip(rfm.feature_importances_, X.columns), reverse=True)

[(0.5508897376719668, 'num_of_bedrooms'),
 (0.10178112466670115, 'avg_tax_rate'),
 (0.05086418129737993, 'max_tax_rate'),
 (0.049303954034685224, 'max_score_ele'),
 (0.04802177447843486, 'max_score_mid'),
 (0.04617197800338567, 'max_score_high'),
 (0.013874987538959598, 'est_pop'),
 (0.01320097825428625, 'auto_theft'),
 (0.008105847159130522, 'max_std_cnt_mid'),
 (0.007147288527137861, 'max_std_cnt_high'),
 (0.006635308473985666, 'max_std_cnt_ele'),
 (0.006591886410875505, 'min_tax_rate'),
 (0.0065560811921635325, 'median_hh_income'),
 (0.00587519542108186, 'poverty_rate'),
 (0.005301426023297685, 'avg_exp_high'),
 (0.005171473613804336, 'avg_exp_mid'),
 (0.004878281742122736, 'poverty_count'),
 (0.004748583403979387, 'avg_exp_ele'),
 (0.004734453395901978, 'avg_score_ele'),
 (0.00466841897510522, 'avg_score_high'),
 (0.004539606666754304, 'max_exp_high'),
 (0.0041632919969454025, 'max_exp_mid'),
 (0.003616624557048896, 'max_exp_ele'),
 (0.003387327530664544, 'avg_score_mid'),
 (0.0030119526150060747, 'min_exp_high'),
 (0.0029064326267987106, 'avg_std_cnt_mid'),
 (0.002791857430587023, 'avg_std_cnt_ele'),
 (0.0023914650973150273, 'burglary'),
 (0.0023431898922829106, 'min_exp_ele'),
 (0.002310268256963613, 'avg_std_cnt_high'),
 (0.0021209370729992566, 'larceny'),
 (0.0020982341155862056, 'robbery'),
 (0.0020967145131636075, 'min_score_mid'),
 (0.0020285133791127044, 'min_exp_mid'),
 (0.001766956237106356, 'min_score_ele'),
 (0.0017645595462930101, 'min_std_cnt_ele'),
 (0.0017588863936860545, 'murder'),
 (0.0017500951123844758, 'rape'),
 (0.0016337909969563757, 'min_std_cnt_mid'),
 (0.0014712150266989973, 'assault'),
 (0.0014025438613368684, 'min_std_cnt_high'),
 (0.0013188859542783247, 'min_score_high'),
 (0.0010234528702922465, 'year'),
 (0.0005835700397524913, 'apr_30'),
 (0.0004952522011235692, 'points_30'),
 (0.0003607902417933904, 'apr_15'),
 (0.0003406254826839556, 'points_15')]

In [24]:
predictions = rfm.predict(X_test)
print(f"Training Data Score: {rfm.score(X_train, y_train)}")
print(f"Testing Data Score: {rfm.score(X_test, y_test)}")
print(f"Production Data Score: {rfm.score(X, y)}")

Training Data Score: 0.9914174536440797
Testing Data Score: 0.9387155037467712
Production Data Score: 0.9800095876548363

In [25]:
from sklearn.metrics import mean_squared_error as MSE

In [26]:
MSE_score = MSE(y_test,predictions)
print("Mean Squared Error: ",MSE_score.mean())
print("Root Mean Squared Error: ",np.sqrt(MSE_score.mean()))

Mean Squared Error:  1803130185.5700846
Root Mean Squared Error:  42463.28043816309

# Hyperparameter Tuning

In [17]:
# Get randomforest params
rfm.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 200,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [97]:
# Create the GridSearchCV model
param_grid = {
    'n_estimators': [200, 100, 150],
    'max_features': [1, 'sqrt', 'log2'],
    'criterion': ['squared_error', 'absolute_error'],
    'max_depth': [5, 10]
}
grid = GridSearchCV(rfm, param_grid, cv=5, verbose=3)

In [98]:
# Train the model with GridSearch
grid.fit(X_train, y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=200;, score=0.293 total time=   0.3s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=200;, score=0.307 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=200;, score=0.075 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=200;, score=0.137 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=200;, score=0.179 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=100;, score=0.309 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=100;, score=0.302 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=100;, score=0.109 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=100;, score=0.130 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=100;, score=0.190 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=150;, score=0.308 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=150;, score=0.243 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=150;, score=0.092 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=150;, score=0.102 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=1, n_estimators=150;, score=0.184 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.609 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.585 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.426 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.489 total time=   0.2s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.517 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.588 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.549 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.432 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.519 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.504 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.613 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.582 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.467 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.507 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.535 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.576 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.518 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.367 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.482 total time=   0.3s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.439 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.538 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.511 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.404 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.476 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.484 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.581 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.546 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.364 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.380 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.435 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=200;, score=0.476 total time=   0.3s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=200;, score=0.377 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=200;, score=0.225 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=200;, score=0.333 total time=   0.2s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=200;, score=0.381 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=100;, score=0.472 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=100;, score=0.353 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=100;, score=0.233 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=100;, score=0.327 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=100;, score=0.325 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=150;, score=0.455 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=150;, score=0.361 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=150;, score=0.202 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=150;, score=0.324 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=1, n_estimators=150;, score=0.312 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.750 total time=   0.3s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.671 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.544 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.684 total time=   0.2s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.687 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.698 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.708 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.530 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.700 total time=   0.1s

[CV 5/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.671 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.743 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.702 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.594 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.672 total time=   0.2s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.676 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.690 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.667 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.524 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.667 total time=   0.2s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.675 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.665 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.730 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.534 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.644 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.600 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.696 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.656 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.514 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.576 total time=   0.3s
[CV 5/5] END criterion=squared_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.639 total time=   0.3s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=200;, score=0.268 total time=   0.3s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=200;, score=0.240 total time=   0.3s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=200;, score=0.012 total time=   0.3s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=200;, score=0.195 total time=   0.4s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=200;, score=0.208 total time=   0.6s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=100;, score=0.291 total time=   0.1s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=100;, score=0.306 total time=   0.1s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=100;, score=0.046 total time=   0.1s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=100;, score=0.195 total time=   0.1s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=100;, score=0.151 total time=   0.1s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=150;, score=0.318 total time=   0.2s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=150;, score=0.280 total time=   0.2s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=150;, score=0.033 total time=   0.2s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=150;, score=0.227 total time=   0.2s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=1, n_estimators=150;, score=0.117 total time=   0.3s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.571 total time=   0.7s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.553 total time=   0.6s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.313 total time=   0.8s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.548 total time=   0.8s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=200;, score=0.545 total time=   0.7s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.608 total time=   0.2s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.561 total time=   0.3s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.331 total time=   0.6s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.558 total time=   0.3s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=100;, score=0.529 total time=   0.3s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.568 total time=   0.4s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.550 total time=   0.5s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.350 total time=   0.4s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.496 total time=   0.4s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=sqrt, n_estimators=150;, score=0.497 total time=   0.6s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.571 total time=   0.8s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.530 total time=   0.8s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.275 total time=   0.7s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.479 total time=   0.8s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=200;, score=0.517 total time=   0.6s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.551 total time=   0.3s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.568 total time=   0.3s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.249 total time=   0.3s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.527 total time=   0.3s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=100;, score=0.464 total time=   0.3s
[CV 1/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.522 total time=   0.5s
[CV 2/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.502 total time=   0.6s
[CV 3/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.310 total time=   0.5s
[CV 4/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.482 total time=   0.5s
[CV 5/5] END criterion=absolute_error, max_depth=5, max_features=log2, n_estimators=150;, score=0.477 total time=   0.5s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=200;, score=0.406 total time=   0.5s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=200;, score=0.356 total time=   0.4s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=200;, score=0.185 total time=   0.4s

[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=200;, score=0.288 total time=   0.4s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=200;, score=0.297 total time=   0.3s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=100;, score=0.425 total time=   0.1s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=100;, score=0.375 total time=   0.1s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=100;, score=0.153 total time=   0.1s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=100;, score=0.311 total time=   0.1s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=100;, score=0.316 total time=   0.1s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=150;, score=0.421 total time=   0.3s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=150;, score=0.366 total time=   0.2s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=150;, score=0.135 total time=   0.2s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=150;, score=0.275 total time=   0.2s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=1, n_estimators=150;, score=0.305 total time=   0.2s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.717 total time=   0.7s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.681 total time=   0.7s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.516 total time=   0.8s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.675 total time=   0.8s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=200;, score=0.683 total time=   0.8s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.712 total time=   0.3s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.662 total time=   0.3s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.550 total time=   0.3s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.690 total time=   0.3s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=100;, score=0.669 total time=   0.3s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.730 total time=   0.6s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.667 total time=   0.5s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.474 total time=   0.6s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.670 total time=   0.5s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=sqrt, n_estimators=150;, score=0.689 total time=   0.7s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.664 total time=   0.7s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.601 total time=   0.8s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.494 total time=   0.9s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.606 total time=   0.7s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=200;, score=0.617 total time=   0.7s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.670 total time=   0.4s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.648 total time=   0.3s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.423 total time=   0.4s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.613 total time=   0.3s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=100;, score=0.636 total time=   0.5s
[CV 1/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.674 total time=   0.6s
[CV 2/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.614 total time=   0.5s
[CV 3/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.438 total time=   0.5s
[CV 4/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.632 total time=   0.5s
[CV 5/5] END criterion=absolute_error, max_depth=10, max_features=log2, n_estimators=150;, score=0.596 total time=   0.5s

GridSearchCV(cv=5, estimator=RandomForestRegressor(n_estimators=200),
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_depth': [5, 10],
                         'max_features': [1, 'sqrt', 'log2'],
                         'n_estimators': [200, 100, 150]},
             verbose=3)

In [24]:
print(grid.best_params_)
print(grid.best_score_)

{'criterion': 'squared_error', 'max_depth': None, 'max_features': 'sqrt', 'n_estimators': 200}
0.6897713345270442

In [25]:
rfm_tuned = RandomForestRegressor(n_estimators=200,criterion= 'squared_error', max_features= 'sqrt', max_depth= None )
rfm_tuned.fit(X_train, y_train)

RandomForestRegressor(max_features='sqrt', n_estimators=200)

In [26]:
predictions = rfm_tuned.predict(X_test)
print(f"Training Data Score: {rfm_tuned.score(X_train, y_train)}")
print(f"Testing Data Score: {rfm_tuned.score(X_test, y_test)}")
print(f"Production Data Score: {rfm_tuned.score(X, y)}")

Training Data Score: 0.9612647283623311
Testing Data Score: 0.7643403189122575
Production Data Score: 0.9186384635917161

In [28]:
MSE_score = MSE(y_test,predictions)
print("Mean Squared Error: ",MSE_score.mean())
print("Root Mean Squared Error: ",np.sqrt(MSE_score.mean()))

Mean Squared Error:  6933647341.006582
Root Mean Squared Error:  83268.52551238422

The base model works better in this case.

# Export model

In [94]:
# Fit the data into model
rfm = RandomForestRegressor(n_estimators=200)
rfm.fit(X, y)

RandomForestRegressor(n_estimators=200)

In [95]:
print(f"Production Data Score: {rfm.score(X, y)}")

Production Data Score: 0.9938475438744534

In [96]:
#  save the model
filename = '../Models/NJ_rfm_house_price.sav'
joblib.dump(rfm, filename)

['../Models/NJ_rfm_house_price.sav']

# Array for prediction

In [2]:
rfm = joblib.load('../Models/NJ_rfm_house_price.sav')

In [37]:
county='UNION'
beds=3
year = 2026
df_filtered=df[(df['county_name']==county)]
county_label=ref_df[ref_df['county_name']==county]['county_label'].values[0]
best_array = df_filtered[(df_filtered['county_name']==county)&\
              (df_filtered['num_of_bedrooms']==beds)].tail(1)
best_array['year']=year
best_array['county_label']=county_label
best_array.reset_index(drop=True,inplace=True)
best_array

,county_name,year,min_tax_rate,avg_tax_rate,max_tax_rate,murder,rape,robbery,assault,burglary,larceny,auto_theft,avg_std_cnt_ele,avg_exp_ele,avg_score_ele,min_std_cnt_ele,min_exp_ele,min_score_ele,max_std_cnt_ele,max_exp_ele,max_score_ele,avg_std_cnt_mid,avg_exp_mid,avg_score_mid,min_std_cnt_mid,min_exp_mid,min_score_mid,max_std_cnt_mid,max_exp_mid,max_score_mid,avg_std_cnt_high,avg_exp_high,avg_score_high,min_std_cnt_high,min_exp_high,min_score_high,max_std_cnt_high,max_exp_high,max_score_high,est_pop,apr_30,points_30,apr_15,points_15,num_of_bedrooms,house_value_index,median_hh_income,poverty_count,poverty_rate,county_label
0,UNION,2026,2.16,8.55,29.27,31.00,89.00,455.00,843.00,745.00,"5,832.00","1,229.00",626.08,"9,387.66",45.65,141,"5,766.00",6.10,2182,"15,980.00",99.20,626.08,"9,387.66",45.65,141,"5,766.00",6.10,2182,"15,980.00",99.20,626.08,"9,387.66",45.65,141,"5,766.00",6.10,2182,"15,980.00",99.20,555394,3.11,0.73,2.60,0.69,3,"377,759.26",83189,50517,9.20,19

In [50]:
county='UNION'
beds=3
year = 2021
df_filtered=df[(df['county_name']==county)]
corr = df_filtered.corr()
corr.fillna(0, inplace=True)
county_label=ref_df[ref_df['county_name']==county]['county_label'].values[0]
best_array = df[(df['county_name']==county)&\
              (df['num_of_bedrooms']==beds)].tail(1)
best_array['year']=year
best_array['county_label']=county_label
for i in best_array.drop(['county_name', 'year', 'house_value_index', 'county_label'],axis=1).columns.tolist():
    best_array[i]=abs(best_array[i]+(year-2020)*corr.loc['year',i])
best_array.reset_index(drop=True,inplace=True)
best_array

,county_name,year,min_tax_rate,avg_tax_rate,max_tax_rate,murder,rape,robbery,assault,burglary,larceny,auto_theft,avg_std_cnt_ele,avg_exp_ele,avg_score_ele,min_std_cnt_ele,min_exp_ele,min_score_ele,max_std_cnt_ele,max_exp_ele,max_score_ele,avg_std_cnt_mid,avg_exp_mid,avg_score_mid,min_std_cnt_mid,min_exp_mid,min_score_mid,max_std_cnt_mid,max_exp_mid,max_score_mid,avg_std_cnt_high,avg_exp_high,avg_score_high,min_std_cnt_high,min_exp_high,min_score_high,max_std_cnt_high,max_exp_high,max_score_high,est_pop,apr_30,points_30,apr_15,points_15,num_of_bedrooms,house_value_index,median_hh_income,poverty_count,poverty_rate,county_label
0,UNION,2021,1.27,7.68,30.25,31.60,89.10,454.06,843.80,744.00,"5,831.17","1,228.23",625.86,"9,387.07",45.87,141.09,"5,765.23",6.52,"2,181.07","15,980.00",99.54,625.86,"9,387.07",45.87,141.09,"5,765.23",6.52,"2,181.07","15,980.00",99.54,625.86,"9,387.07",45.87,141.09,"5,765.23",6.52,"2,181.07","15,980.00",99.54,"555,394.32",2.40,1.55,2.02,1.42,3.00,"377,759.26","83,189.90","50,517.07",9.38,19

In [51]:
rfm.predict(best_array.drop(['county_name','house_value_index', 'county_label'],axis=1))[0]

381935.6765148408

In [34]:
df[(df[f'county_name']==county)&\
   (df['num_of_bedrooms']==beds)][['county_name', 'year',\
                                   'num_of_bedrooms','house_value_index']].tail(1)

    county_name  year  num_of_bedrooms  house_value_index
412       UNION  2020                3         377,759.26